name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call: # to reuse by release workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code.
      uses: actions/checkout@v3
    - name: Build PDFs.
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          Satzung.tex
          
    - name: Upload PDFs temporary.
      uses: actions/upload-artifact@v3.1.1
      with:
        name: PDFs
        path: "*.pdf"
        retention-days: 5
        if-no-files-found: error
